version: '3.3'

services:
  rats:
    build:
      context: ./services/rats
      dockerfile: Dockerfile-dev
    volumes:
      - './services/rats:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@rats-db:5432/rats_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@rats-db:5432/rats_test
    depends_on:
      - rats-db

  rats-db:
    build:
      context: ./services/rats/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - rats
      - client

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile-dev
    volumes:
      - './services/client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_RATS_SERVICE_URL=${REACT_APP_RATS_SERVICE_URL}
    depends_on:
      - rats
