version: '3.3'

services:
  rats:
    build:
      context: ./services/rats
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@rats-db:5432/rats_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@rats-db:5432/rats_test
    depends_on:
      - rats-db

  rats-db:
    build:
      context: ./services/rats/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - rats
      - client

  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - REACT_APP_RATS_SERVICE_URL=${REACT_APP_RATS_SERVICE_URL}
    ports:
      - '3007:80'
    depends_on:
      - rats
